name: Actualizar Precio USDT Bolivia

on:
  schedule:
    - cron: '0 * * * *'  # Esto corre al minuto 0 de cada hora
  workflow_dispatch:      # Esto te permite darle a un botón y probarlo YA

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests

      - name: Ejecutar script de Hexx
        run: python bot.py

      - name: Guardar cambios en el repo
        run: |
          git config --global user.name 'Hexx-Bot'
          git config --global user.email 'salvatierra.tradingfinanzas@gmail.com'
          git add data.json
          git commit -m "Actualización automática de precio" || exit 0
          git push
