name: Bot-USDT
on:
  schedule:
    - cron: '*/30 * * * *'  # <--- ESTE ES EL DESPERTADOR (Cada hora)
  workflow_dispatch:      # <--- ESTE ES EL BOTÓN MANUAL (Para pruebas)
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install requests
        
      - name: Ejecutar Bot
        run: python bot.py
      - name: Guardar en GitHub
        run: |
          git config --global user.name 'Hexx-Bot'
          git config --global user.email 'bot@hexx.com'
          git add data.json
          git commit -m "update" || exit 0
          git push origin main   
      # - run: python bot.py
      # - run: |
      #     git config --global user.name 'Hexx-Bot'
      #     git config --global user.email 'bot@hexx.com'
      #     git add data.json
      #     git commit -m "update" || exit 0
      #     git push
      #     git push origin main --force



    
      
  
