name: Bot-USDT
on:
  schedule:
    - cron: '*/30 * * * *'  # <--- ESTE ES EL DESPERTADOR (Cada hora)
  workflow_dispatch:      # <--- ESTE ES EL BOTÓN MANUAL (Para pruebas)
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install requests
        
      - name: Ejecutar Bot
        run: python bot.py


      - name: Ejecutar Bot
        run: python bot.py

      - name: Forzar Guardado Total
        run: |
          git config --global user.name 'Hexx-Bot'
          git config --global user.email 'bot@hexx.com'
          
          # Truco: tocamos el archivo para actualizar su fecha de modificación
          touch data.json 
          
          git add data.json
          
          # Forzamos el commit con la fecha y hora para que siempre sea único
          git commit -m "Registro Hexx: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No hay cambios, pero forzamos"
          git push origin main  
  




    
      
  
